pipeline {
    agent {
        docker {
            image 'docker:24.0.5'  
            args '-v /var/run/docker.sock:/var/run/docker.sock'
        }
    }

    environment {
        IMAGE_NAME = "devops-pipeline"
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                sh 'docker build -t $IMAGE_NAME .'
            }
        }

        stage('Test') {
            steps {
                echo 'T'
            }
        }

        stage('Package') {
            steps {
                echo 'P'
            }
        }

        stage('Deploy') {
            steps {
                echo 'D'
            }
        }
    }
}

/*pipeline {
    agent any

    stages {
        stage('Clone') {
            steps {
                git branch: 'master', 
                url: 'https://github.com/TheAngel11/DevOpsPipeline'
            }
        }

        stage('Build') {
            steps {
                script {
                    docker.build("devops-pipeline")
                }
            }
        }

        stage('Test') {
            steps {
                sh 'docker run --rm devops-pipeline pytest || echo "Tests skipped"'
            }
        }

        stage('Package') {
            steps {
                script {
                    sh 'docker save devops-pipeline -o devops-pipeline.tar'
                }
            }
        }

        stage('Deploy') {
            steps {
                script {
                    sh 'docker stop devops-pipeline-container || true'
                    sh 'docker rm devops-pipeline-container || true'
                    sh 'docker run -d -p 5000:5000 --name devops-pipeline-container devops-pipeline'
                }
            }
        }
    }
}*/